eb030a_data_ranges = {
    "school_year": "AA11",
    "group": "AA11",
    "dt": "E13",
    "headers": "A17:AE17",
    "students": "A18:AE60",
}
s07a_data_ranges = {
    "school_year": "Y12",
    "group": "Y12",
    "dt": "E16",
    "headers": "A20:AF20",
    "students": "A21:AF100",
}

eb058f_data_ranges = {
    "school_year": "A11",
    "group": "A11",
    "dt": "I13",
    "headers": "A15:M15",
    "students": "A16:M100",
}


eb021_data_ranges = {
    "school_year": "BC10",
    "process_no": "M16",
    "name": "O12",
    "bdate": "N24",
    "gender": "L21",
    "special_education_needs": "BB40",
    "naturality": "J54",
    "nationality": "K59",
    "address": "Y52",
    "zip_code": "AD58",
    "personal_email": "AQ23",
    "phone_number": "AT17",
    "cellphone_number": "AU21",
    "ase": "AV30",
    "number_family_members": "AZ34",
    "foreign_language_I": "AW47",
    "foreign_language_II": "AX50",
    "computer_at_home": "BA56",
    "internet_at_home": "AY60",
    "cc": "F33",
    "cc_archive": "F37",
    "cc_emission_date": "G40",
    "cc_validity_date": "G43",
    "passport": "H50",
    "NIF": "Z32",
    "health_number": "AE36",
    "NISS": "AL36",
    "father_name": "AB67",
    "father_naturality": "AG69",
    "father_nationality": "AH71",
    "father_contacts": "AD73",
    "father_school": "AI75",
    "father_job": "AE77",
    "father_job_situation": "AI79",
    "mother_name": "AB83",
    "mother_naturality": "AG85",
    "mother_nationality": "AH87",
    "mother_contacts": "AE89",
    "mother_school": "AI91",
    "mother_job": "AE93",
    "mother_job_situation": "AI95",
    "guardian_relation": "W98",
    "guardian_name": "AB100",
    "guardian_naturality": "AG102",
    "guardian_nationality": "AH104",
    "guardian_contacts": "AD106",
    "guardian_email": "AB108",
    "guardian_address": "AC110",
    "guardian_zip_code": "AG112",
    "guardian_school": "AI114",
    "guardian_job": "AE117",
    "guardian_job_situation": "AI119",
}

p072_data_ranges = {
    "school_year": "B9",
    "process_no": "H14",
    "name": "G12",
    "bdate": "H17",
    "gender": "H16",
    "special_education_needs": "AA24",
    "naturality": "C29",
    "nationality": "C32",
    "address": "L30",
    "zip_code": "L33",
    "personal_email": "AA17",
    "phone_number": "AA14",
    "cellphone_number": "AA16",
    "ase": "AA20",
    "number_family_members": "AA22",
    "foreign_language_I": "AA27",
    "foreign_language_II": "AA29",
    "computer_at_home": "AA32",
    "internet_at_home": "AA33",
    "cc": "C24",
    "cc_validity_date": "C26",
    "NIF": "L20",
    "health_number": "L24",
    "NISS": "T20",
    "father_name": "S35",
    "father_naturality": "S36",
    "father_nationality": "S37",
    "father_contacts": "S38",
    "father_school": "S39",
    "father_job": "S41",
    "father_job_situation": "S42",
    "mother_name": "S44",
    "mother_naturality": "S45",
    "mother_nationality": "S46",
    "mother_contacts": "S47",
    "mother_school": "S48",
    "mother_job": "S50",
    "mother_job_situation": "S51",
    "guardian_relation": "R53",
    "guardian_name": "R53",
    "guardian_naturality": "R55",
    "guardian_nationality": "R56",
    "guardian_contacts": "R57",
    "guardian_email": "R58",
    "guardian_address": "R59",
    "guardian_zip_code": "R60",
    "guardian_school": "R61",
    "guardian_job": "R64",
    "guardian_job_situation": "R65",
}
